name: pennywise
description: A new Flutter project

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '^2.12.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Other development dependencies...

flutter:
  uses-material-design: true
